### ISSUE TITLE
Possible duplicity

### ISSUE THREAD

**Issue by AdrianRaFo** [47deg/github4s#136]
We have postAuth and postOAuth in httpClient.
The first receive a header built by the method in Auth API.
The second not receives a header but add one by himself.

Is possible delete postOuth and pass his header on the method?

**Comment by bilki** [comment]
Does this suggestion still apply? Both `postAuth` and `postOAuth` in the current master branch receive a `headers` argument of type `Map[String, String]`, but the first one builds the url from the auth method, and the second one just posts into the provided `url` parameter.

I would keep them the way they are right now because semantics are different. Do you mind if we close this ticket?
