### ISSUE TITLE
Documentation not updated

### ISSUE THREAD

**Issue by BenFradet** [47deg/github4s#167]
I think there has been an issue with the release as I don't think the docs have been updated at: http://47deg.github.io/github4s/.

For example, https://github.com/47deg/github4s/blob/master/docs/src/main/tut/docs.md#using-catseffectio is missing from http://47deg.github.io/github4s/docs.html.

Relevant travis log: https://travis-ci.org/47deg/github4s/jobs/279614630#L8146

**Comment by juanpedromoreno** [comment]
I've published manually the latest docs (http://47deg.github.io/github4s/ should be up-to-date), and I've logged a new issue at `sbt-org-policies` plugin: https://github.com/47deg/sbt-org-policies/issues/656

I'm closing this for now since I think, it should be fixed outside this project.

Thanks for reporting about this, Ben.
