### ISSUE TITLE
PullRequest's head missing

### ISSUE THREAD

**Issue by BenFradet** [47deg/github4s#89]
I noticed the [`head`](https://github.com/47deg/github4s/blob/master/github4s/jvm/src/test/scala/github4s/utils/FakeResponses.scala#L848) field is missing from the [`PullRequest`](https://github.com/47deg/github4s/blob/master/github4s/shared/src/main/scala/github4s/free/domain/PullRequest.scala#L19-L33) case class.

Would you guys mind if I added it? Or is there another reason why it's not included?

**Comment by fedefernandez** [comment]
It was intentional but without any particular reason. We usually don't create complete models, mainly because GitHub doesn't provide a detailed information about what fields are optional or nullables.

Later, when we need a specific field we add it in another pr. Thanks for the ticket, we can use it for add the field.

**Comment by BenFradet** [comment]
>It was intentional but without any particular reason. We usually don't create complete models, mainly because GitHub doesn't provide a detailed information about what fields are optional or nullables.

Makes total sense.

>Later, when we need a specific field we add it in another pr. Thanks for the ticket, we can use it for add the field.

Yup, that's why I raised the ticket as I actually need the `head` field, I'll open a PR tomorrow :+1:
